spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/router?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: test
      password: test
mybatis:
   mapperLocations: classpath:/mapper/*.xml
