spring:
  datasource:
      url: jdbc:mysql://192.168.1.128:3306/router?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: zxl
      password: hxroot123
mybatis:
   mapperLocations: classpath:/mapper/*.xml
